name: Curate an OSS Package

permissions:
  id-token: write

on:
  workflow_dispatch:

jobs:
  Initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: github-oidc-integration
          oidc-audience: jfrog-github

      - name: List Package Managers
        id: list-package-manager
        run: |
          echo $(npm --version)
          echo $(mvn --version)
          echo $(pip --version)
          echo $(docker --version)


      - name: Extract Package Request
        id: extract-package-request
        run: |
          packageRequest=$(jq . < input/requested-packages.json)
          echo "packageRequest=$packageRequest >> $GITHUB_OUTPUT

      - name: Extract and set packageType
        id: extract-package-type
        run: |
          packageType=$(jq -r '.packageType' < input/requested-packages.json)
          echo "packageType=$packageType" >> $GITHUB_OUTPUT

      - name: Validate Package Request
        id: validate-package-request
        run: |
          echo ${{ steps.extract-package-request.outputs.packageRequest }}

      - name: Validate Package Type
        id: validate-package-type
        run: |
          echo ${{ steps.extract-package-type.outputs.packageType }}

  Curate-Python:
    runs-on: ubuntu-latest
    needs: extract_package_type
    if: ${{ needs.extract-package-type.outputs.packageType == 'python' }}
    run:
      working-directory: ./pip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run Python Job
        run: |
          echo "Running Python-specific job"
          # Add your python-specific commands here
          pip3 install -r 
          python curate-python.py