name: Curate an OSS Package

permissions:
  id-token: write

on:
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      packageType: ${{ steps.extract-package-type.outputs.packageType }}
      packageRequest: ${{ steps.extract-package-request.outputs.packageRequest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: github-oidc-integration
          oidc-audience: jfrog-github

      - name: List Package Managers
        id: list-package-manager
        run: |
          echo NPM Version: $(npm --version)
          echo Maven Version: $(mvn --version)
          echo Pip Version: $(pip --version)
          echo Docker Version: $(docker --version)

      - name: Extract Package Request
        id: extract-package-request
        run: |
          packageRequest=$(jq -c '.' < input/requested-packages.json)
          echo "packageRequest=$packageRequest" >> $GITHUB_OUTPUT

      - name: Extract and set packageType
        id: extract-package-type
        run: |
          packageType=$(jq -r '.packageType' < input/requested-packages.json)
          echo "packageType=$packageType" >> $GITHUB_OUTPUT

      - name: Validate Package Request
        id: validate-package-request
        run: |
          echo ${{ steps.extract-package-request.outputs.packageRequest }}

      - name: Validate Package Type
        id: validate-package-type
        run: |
          echo ${{ steps.extract-package-type.outputs.packageType }}

  curate-python:
    runs-on: ubuntu-latest
    needs: initialize
#    env:
#      res_curatepypi_payload: ${{ needs.initialize.outputs.packageRequest }}
    if: ${{ needs.initialize.outputs.packageType == 'python' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Run Python Job
        working-directory: ./pip
        env:
          res_curatepypi_payload: ${{ needs.initialize.outputs.packageRequest }}
        run: |
          printenv
          echo "Running Python-specific job"
          pip install -r requirements.txt
          which python
          python curate-python.py